# Docker Composeのバージョンを指定
version: '3.8'

# 共通の環境変数を定義するYAMLアンカー
x-common-environment: &common-environment
  environment:
    - REDIS_URL=redis://redis:6379/0

# 起動するサービス（コンテナ）を定義
services:
  # 1. APIサーバー (FastAPI)
  api:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./downloads:/app/downloads
    <<: *common-environment
    depends_on:
      redis:
        condition: service_healthy

  # 2. バックグラウンドワーカー (Celery)
  worker:
    build: ./app
    command: celery -A celery_instance.celery_app worker --loglevel=info
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
    <<: *common-environment
    depends_on:
      redis:
        condition: service_healthy

  # 3. メッセージブローカー (Redis)
  redis:
    image: "redis:7-alpine"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
