# Docker Composeのバージョンを指定
version: '3.8'

# 起動するサービス（コンテナ）を定義
services:
  # 1. APIサーバー (FastAPI)
  api:
    build: ./yt-dlp
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./yt-dlp:/app
      - ./yt-dlp/downloads:/app/downloads
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  # 2. バックグラウンドワーカー (Celery)
  worker:
    build: ./yt-dlp
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - ./yt-dlp:/app
      - ./yt-dlp/downloads:/app/downloads
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  # 3. メッセージブローカー (Redis)
  redis:
    image: "redis:7-alpine"
    volumes:
      - redis_data:/data # Redisのデータを永続化するためのボリューム

# 永続化に使用する名前付きボリュームを定義
volumes:
  redis_data:
