# docker-compose.yml

version: '3.8'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # Caddyのデータを永続化するためのボリューム（証明書など）
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

  api:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./app
    command: celery -A celery_instance.celery_app worker --loglevel=info
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: "redis:7-alpine"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  caddy_data:
  caddy_config: