# GitHub Actionsワークフローの名前
name: CI

# ワークフローが実行されるトリガーを定義
on:
  # mainブランチへのプッシュ時に実行
  push:
    branches: [ main ]
  # mainブランチへのプルリクエスト時に実行
  pull_request:
    branches: [ main ]

# 実行されるジョブを定義
jobs:
  # 'test-api'という名前に変更
  test-api:
    # 最新のUbuntu環境で実行
    runs-on: ubuntu-latest

    # ジョブのステップを定義
    steps:
    # 1. リポジトリのコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Docker Composeでアプリケーション全体をバックグラウンドで起動
    - name: Start services via Docker Compose
      run: docker compose up -d

    # 3. 依存関係のインストールが完了するまで少し待機
    - name: Wait for services to be ready
      run: sleep 10

    # 4. コンテナ内でpytestを実行 (APIテストのみが実行される)
    - name: Run API tests inside container
      run: docker compose exec -T api pytest